---
- client:
    ssh_client_ip_address: 10.6.1.2
    ssh_client_username: administrator
    ssh_client_password: Password2
    server_list_to_test:
    - ssh_server_ip_address: 10.6.1.2
      ssh_server_username: administrator
      ssh_server_password: Password2
      try_to_spawn_socket_on_remote_server: true
      socket_to_test:
      - address: merda
        port: "3128"
        under_load_balancer: false
        load_balancer_address:
      - address: test-server
        port: "9998"
        under_load_balancer: false
        load_balancer_address:
      - address: 10.0.2.10
        port: "9999"
        under_load_balancer: true
        load_balancer_address: 10.10.10.134:8080
    - ssh_server_ip_address:
      ssh_server_username:
      ssh_server_password:
      try_to_spawn_socket_on_remote_server: false
      socket_to_test:
      - address: 10.6.222.2
        port: "3128"
        try_to_spawn_socket_on_remote_server: false
        under_load_balancer: false
        load_balancer_address:
      - address: 172.26.166.49
        port: "80"
        under_load_balancer: false
        load_balancer_address: